apiVersion: v1
kind: Service
# a standard Service except exterName will be specified below
metadata:
  name: mysql-externalname-service
  # this name will be used in the env: variables of the UserMgmtWebApp deployment yaml.
  # this is also used in the initContainer command string of the UserMgmtWebApp deployment yaml.
  # the initContainer just pings the Cloud SQL to make sure it is up, prior to bringing up the UserMgmtWebApp container.
spec:
  type: ExternalName
  #externalName: 35.202.247.53
  externalName: 10.122.0.3
  # this address is shown in the overview after we have created the private Cloud SQL instance
  # as expected it in on the 10.122.0.0/16 private VPC network that was created for the peering.
  # the 10.122.0.0/16 network can be seen in the default VPC under the Private Service Connection tab

  # the only difference between public Cloud SQL and private SQL is that this 
  # externalName will be the private ip addres of the Cloud SQL
  # the rest of the yaml files are the same.